linters:
  enable-all: true
  disable:
    - bodyclose
    - cyclop
    - errcheck
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - gosec
    - lll
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - revive
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake

