linters:
  enable-all: true
  disable:
    - cyclop
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - gomnd
    - lll
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - revive
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint

linters-settings:
  #
  # The G108 rule throws a false positive. We're not actually vulnerable. If
  # you're not careful the profiling endpoint is automatically exposed on
  # /debug/pprof if you import net/http/pprof. See this link:
  #
  #   https://mmcloughlin.com/posts/your-pprof-is-showing
  #
  gosec:
    excludes:
      - G108

  tagliatelle:
    case:
      rules:
        json: snake

  gofumpt:
    extra-rules: true

  exhaustruct:
    exclude:
      #
      # Because it's easier to read without the other fields.
      #
      - 'GetPayloadsFilters'

      #
      # Structures outside our control that have a ton of settings. It doesn't
      # make sense to specify all of the fields.
      #
      - 'cobra.Command'
      - 'database.*Entry'
      - 'http.Server'
      - 'logrus.*Formatter'
      - 'Options' # redis

      #
      # Excluded because there are private fields (not capitalized) that are
      # not initialized. If possible, I think these should be altered.
      #
      - 'Datastore'
      - 'Housekeeper'
      - 'MockBeaconClient'
      - 'RelayAPI'
      - 'Webserver'
