# https://golangci-lint.run/usage/linters
linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - lll
    - musttag
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - interfacebloat
    - exhaustruct
    - tenv
    - gocognit
    - dupl

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  #
  # The G108 rule throws a false positive. We're not actually vulnerable. If
  # you're not careful the profiling endpoint is automatically exposed on
  # /debug/pprof if you import net/http/pprof. See this link:
  #
  #   https://mmcloughlin.com/posts/your-pprof-is-showing
  #
  gosec:
    excludes:
      - G108

  gocognit:
    min-complexity: 85 # default: 30

  gocyclo:
    min-complexity: 70 # default: 30

  gomoddirectives:
    replace-allow-list:
      - github.com/attestantio/go-builder-client
      - github.com/attestantio/go-eth2-client
      - github.com/ethereum/go-ethereum

  maintidx:
    under: 5

  tagliatelle:
    case:
      rules:
        json: snake

  gofumpt:
    extra-rules: true

  exhaustruct:
    exclude:
      #
      # Because it's easier to read without the other fields.
      #
      - 'GetPayloadsFilters'
      #
      # Easier to read with only one of the versioned payloads.
      #
      - 'VersionedSubmitBlindedBlockResponse'
      - 'VersionedExecutionPayload'
      - 'VersionedSignedBuilderBid'

      #
      # Structures outside our control that have a ton of settings. It doesn't
      # make sense to specify all of the fields.
      #
      - 'cobra.Command'
      - 'database.*Entry'
      - 'http.Server'
      - 'logrus.*Formatter'
      - 'Options' # redis

      #
      # Excluded because there are private fields (not capitalized) that are
      # not initialized. If possible, I think these should be altered.
      #
      - 'Datastore'
      - 'Housekeeper'
      - 'MockBeaconClient'
      - 'RelayAPI'
      - 'Webserver'

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - exhaustruct
    - path: database/.*.go
      linters:
        - goconst
    - path: cmd/tool/.*.go
      linters:
        - goconst