package migrations

import (
	"github.com/flashbots/mev-boost-relay/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration008Optimistic = &migrate.Migration{
	Id: "008-optimistic",
	Up: []string{
		`
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD optimistic_submission bool NOT NULL default false;
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD decode_duration       bigint NOT NULL default 0;
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD prechecks_duration    bigint NOT NULL default 0;
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD simulation_duration   bigint NOT NULL default 0;
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD redis_update_duration bigint NOT NULL default 0;
		ALTER TABLE ` + vars.TableBuilderBlockSubmission + ` ADD total_duration        bigint NOT NULL default 0;
	`, `
		ALTER TABLE ` + vars.TableBlockBuilder + ` ADD is_optimistic  bool NOT NULL default false;
		ALTER TABLE ` + vars.TableBlockBuilder + ` ADD collateral     NUMERIC(48, 0) NOT NULL default 0;
		ALTER TABLE ` + vars.TableBlockBuilder + ` ADD builder_id     varchar(98) NOT NULL default '';
	`, `
		CREATE TABLE IF NOT EXISTS ` + vars.TableBuilderDemotions + `(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,
			
			submit_block_request          json,
			signed_beacon_block  	      json,
			signed_validator_registration json,

			epoch bigint NOT NULL,
			slot  bigint NOT NULL,
			
			builder_pubkey  varchar(98) NOT NULL,
			proposer_pubkey varchar(98) NOT NULL,
			
			value NUMERIC(48, 0),
			
			fee_recipient varchar(42) NOT NULL,
			
			block_hash varchar(66) NOT NULL,
			
			sim_error text NOT NULL,
			
			UNIQUE (builder_pubkey, block_hash)
		);
	`,
	},
	Down: []string{},

	DisableTransactionUp:   true,
	DisableTransactionDown: true,
}
