package migrations

import (
	"github.com/flashbots/mev-boost-relay/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration011HeaderSubmissionTable = &migrate.Migration{
	Id: "011-header-submission-table",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + ` (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,

			-- bidtrace data
			signature            text NOT NULL,

			slot        bigint NOT NULL,
			parent_hash varchar(66) NOT NULL,
			block_hash  varchar(66) NOT NULL,

			builder_pubkey         varchar(98) NOT NULL,
			proposer_pubkey        varchar(98) NOT NULL,
			proposer_fee_recipient varchar(42) NOT NULL,

			gas_used   bigint NOT NULL,
			gas_limit  bigint NOT NULL,

			value  NUMERIC(48, 0),

			-- helpers
			epoch        bigint NOT NULL,
			block_number bigint NOT NULL,
			
			-- tracing
			received_at 			timestamp NOT NULL,
			payload_load_duration 	bigint NOT NULL,
			decode_duration 		bigint NOT NULL,
			prechecks_duration 		bigint NOT NULL,
			signature_duration 		bigint NOT NULL,
			redis_checks_duration 	bigint NOT NULL,
			redis_update_duration 	bigint NOT NULL,
			total_duration 			bigint NOT NULL
		);

		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + `_slot_idx ON ` + vars.TableBuilderHeaderSubmission + `("slot");
		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + `_block_hash_uidx ON ` + vars.TableBuilderHeaderSubmission + `("block_hash");
		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + `_block_number_idx ON ` + vars.TableBuilderHeaderSubmission + `("block_number");
		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + `_builder_pubkey_idx ON ` + vars.TableBuilderHeaderSubmission + `("builder_pubkey");
		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderHeaderSubmission + `_received_idx ON ` + vars.TableBuilderHeaderSubmission + `("received_at" DESC);
	`},
	Down: []string{`
		DROP TABLE IF EXISTS ` + vars.TableBuilderHeaderSubmission + `;
	`},
	DisableTransactionUp:   false,
	DisableTransactionDown: false,
}
